### ISSUE TITLE
KeyError can also be raised

### ISSUE THREAD

**Issue by Bruniz** [willemt/pytest-asyncio-cooperative#18]
I came across an issue where my test session fails at start because some fixture is missing a key. I managed to work around the problem in my environment by just catching KeyError in addition to AttributeError. I do not have access to my environment to try and reproduce the issue, but I'll update this issue once I have. I think though it was related to nested fixtures.

I cloned the repository and all tests still pass after adding the new exception, I would just like to understand what happens so a test for that could also be created.

https://github.com/willemt/pytest-asyncio-cooperative/blob/62c4ad708415eafa675b940c34f323660a66c273/pytest_asyncio_cooperative/fixtures.py#L26

So I'd like to discuss this and then preferably be allowed to merge a fix for this once we fully understand.

**Comment by willemt** [comment]
Thanks for the bug report! If you can get a reproducible example (or test) I'll merge the fix in ASAP.

**Comment by remifontan** [comment]
Hi,

I also encountered such error, and it seems to be triggered when I use parametrize with asyncio_cooperative.

following test:

```
@pytest.mark.asyncio_cooperative
@pytest.mark.parametrize("numseconds", [1])
async def test_async_foo(tmp_path, numseconds):
   
    print("tmp_path", tmp_path)
    now = time.time()
    print("going to sleep at", now)
    await asyncio.sleep(numseconds)

    elapsed = time.time() - now
    print("done, elapsed", elapsed)
```

gave me this error:
```
>                   item._request.param = item._pyfuncitem.callspec.params[fixture.argname]
E                   KeyError: 'tmp_path'

pytest-asyncio-cooperative/pytest_asyncio_cooperative/fixtures.py:26: KeyError

```

**Comment by willemt** [comment]
thanks I was able to reproduce and fix it
fix is in 0.22.0

**Comment by remifontan** [comment]
thanks that fixed that particular issue. I believe I'm encountering some new issues, will make a new ticket

**Comment by meoyawn** [comment]
the issue came back when used with pytest 7.3 & 7.4. No issues with pytest 7.2
