### ISSUE TITLE
functions with @pytest.mark.asyncio_cooperative markings seem to execute first

### ISSUE THREAD

**Issue by ddeanto** [willemt/pytest-asyncio-cooperative#29]
However, I want it so that order is respected since my tests have dependencies.

**Comment by willemt** [comment]
I don't think this is possible sorry! By definition the asynchronous tests can eventually execute in different orders.
I suppose we can make the sync tests run first and the async tests 2nd, but I don't think this solves your problem.

I would recommend making all tests asynchronous and then migrating your dependencies into asynchronous fixtures. You can even use asynchronous locks to ensure the dependencies are executed in a way that makes sense (even with async tests).

Maybe if you can share your use case more I can help find a better solution?

**Comment by andersfylling** [comment]
> However, I want it so that order is respected since my tests have dependencies.

Usually dependencies are defined in fixtures. Tests should not be coupled, nor change some shared state in serial as it can lead to a can of worms. Isolating your test suite would be highly recommended as an alternative approach to this issue. 

Isolated tests should function in a randomize execution order.

**Comment by willemt** [comment]
closing because the nature of pytest-asyncio-cooperative is to not run tests in an expected order
