### ISSUE TITLE
Tests run concurrently but fixtures do not

### ISSUE THREAD

**Issue by gerlero** [willemt/pytest-asyncio-cooperative#36]
First of all, thanks for making this package. AFAICT it's the only `pytest` plugin that will execute the actual test suite concurrently, and I appreciate having that functionality.

My issue appears in the following case:

```python
@pytest.fixture
async def fixture_1():
    ...

@pytest.fixture
async def fixture_2():
    ...

@pytest.mark.asyncio_cooperative
async def test_something(fixture_1, fixture_2):
    ...
```

then, while obtaining the fixtures for `test_something`, `fixture_1` always seems to be fully awaited before `fixture_2` starts executing, even though there's no reason for these features not to run concurrently (i.e., they're both coroutines and neither is a required fixture of the other one). Is there a way to get the same concurrency behavior for fixtures with this package as we get with tests?

**Comment by willemt** [comment]
Wow, I can't believe this has been overlooked.

It should be as simple as swapping out the for loops in fixtures.py with `asyncio.gather`. I'll have a look...
