### ISSUE TITLE
How can I use session fixtures? Right now they're rejected

### ISSUE THREAD

**Issue by asherdiamond** [willemt/pytest-asyncio-cooperative#5]

**Comment by willemt** [comment]
fixed with a0906612c0556da2f5fd64debcf1784d4a37d856

please try installing version 0.10.0

**Comment by asherdiamond** [comment]
thanks! This got me a bit further, but there is now a problem using
'builtin' pytest fixtures, like request
Here is what happens:

=======================================================================================================================
FAILURES
========================================================================================================================
_______________________________________________________________________________________
test_im_send_message[XXX]
_______________________________________________________________________________________

>   item.runtest = lambda: result.result()

../../.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:390:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _
../../.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:243:
in test_wrapper
    fixture_values, teardowns = await fill_fixtures(item)
../../.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:228:
in fill_fixtures
    value, teardowns2 = await fill_fixture_fixtures(
../../.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:195:
in fill_fixture_fixtures
    fixture_values, teardowns = await _fill_fixture_fixtures(
../../.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:66:
in _fill_fixture_fixtures
    dep_fixture = _get_fixture(_fixtureinfo, arg_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _

_fixtureinfo = FuncFixtureInfo(argnames=('tests_bundle', 'X', 'Y', 'Z',
'im_na...='function' baseid=''>], 'device_description': [<FixtureDef
argname='device_description' scope='function' baseid=''>]})
arg_name = 'request'

    def _get_fixture(_fixtureinfo, arg_name):
        """
        Sometimes fixture names clash with plugin fixtures.
        We priortise fixtures that are defined inside the user's module
        """
        fixtures = sorted(
>           _fixtureinfo.name2fixturedefs[arg_name], key=lambda x: not
x.has_location
        )
E       KeyError: 'request'

../../.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytest_asyncio_cooperative/plugin.py:214:
KeyError
