### ISSUE TITLE
Wrong fixture is used if there are same named fixtures in different conftest files

### ISSUE THREAD

**Issue by m-rehanRTB** [willemt/pytest-asyncio-cooperative#60]
If you have nested conftests like:

└── test
    ├── foo
    │   ├── conftest.py
    │   └── test_foo.py
    ├── conftest.py
    └── test_bar.py

And both conftests contains the same named fixture then the one in the conftest.py file closest to the test file should be taken.
In this case test_foo should take fixture from test/foo/conftest.py and test_bar shoud take one from test/conftest.py but in current state both test files would use test/conftest.py

**Comment by willemt** [comment]
closed via https://github.com/willemt/pytest-asyncio-cooperative/pull/61
